name: Build, Gzip, and deploy Node.js app to Azure Web App - redwood-api-test

on:
  push:
    branches:
      - app-service-code
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # Adjust to your preferred Node.js version

      - name: Install yarn
        run: npm install -g yarn

      - name: npm install and build
        run: |
          yarn install
          yarn rw prisma generate
          yarn build api

      - name: Gzip API build
        run: |
          cd dist/api
          find . -type f \( -name "*.js" -o -name "*.json" \) -exec gzip -k -9 {} \;

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: gzipped-node-app
          path: dist/api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: gzipped-node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'redwood-api-test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AE6F692A8C8B45568B9AAEB2CF4FB262 }}
          package: ./dist/api
